---
# tasks file for deploy_mysql

- name: Update apt repo
  apt: update_cache=yes

- name: Install MySql server
  apt: name=mysql-server=8.0.34-0ubuntu0.22.04.1 state=present

- name: Start service
  service: name=mysql state=started enabled=yes

- name: Install pip3
  apt: name=python3-pip state=latest

- name: Install PyMySQL package
  ansible.builtin.pip:
   name: pymysql
